all:
	g++ -std=c++11 *.cpp -o TUW-Server -I/home/jscheil/.sfml/include -L/home/jscheil/.sfml/lib -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -lsfml-network
	./TUW-Server

headers:
	g++ *.hpp

clean:
	rm *.hpp.gch
